---
- name: Set up Apache2 website
  hosts: all
  become: true
  tasks:
  - name: Install Apache2
    apt:
      name: 
      - git
      - apache2
      state: present
  - name: Start Apache2 service
    service:
      name: apache2
      state: started
  - name: Enable Apache2 service
    service:
      name: apache2
      enabled: true
  - name: Remove /var/www/html folder
    file:
      path: /var/www/html
      state: absent
  - name: Clone GitHub repository
    git:
      repo: https://github.com/ThorD125/site.git
      dest: /var/www/html
