---
- hosts: all
  become: true
  vars:
    domain_name: example.com
    document_root: /var/www/html/{{ domain_name }}
  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: present

  - name: Create Apache2 Virtual Host
    template:
      src: configs/apachessl.conf.j2
      dest: /etc/apache2/sites-available/{{ domain_name }}.conf

  - name: Enable Apache2 Virtual Host
    ansible.builtin.shell: "cd /etc/apache2/sites-available && a2ensite {{ domain_name }}.conf"

- openssl_privatekey:
    path: /etc/ssl/localcerts/{{ domain_name }}.key
    size: 2048 

- openssl_csr:
    path: /etc/ssl/localcerts/{{ domain_name }}.csr
    privatekey_path: /etc/ssl/localcerts/{{ domain_name }}.key

- openssl_certificate:
    provider: selfsigned
    path: /etc/ssl/localcerts/{{ domain_name }}.crt
    privatekey_path: /etc/ssl/localcerts/{{ domain_name }}.key
    csr_path: /etc/ssl/localcerts/{{ domain_name }}.csr
 