---
- name: Setup Nginx website
  hosts: all
  become: yes
  vars:
    domain_name: example.com
    document_root: /var/www/html
  tasks:
    - name: Install Nginx
      apt:
        name: 
        - nginx
        - git
        state: present

    - name: Create Nginx configuration file
      template:
        src: configs/nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default

    - name: Remove /var/www/html folder
      file:
        path: /var/www/html
        state: absent
        
    - name: Clone GitHub repository
      git:
        repo: https://github.com/ThorD125/site
        dest: /var/www/html
      register: git_output

    - name: restart nginx
      service:
        name: nginx
        state: restarted
