---
- name: Setup Nginx website
  hosts: all
  become: yes
  tasks:
    - name: Remove /etc/nginx/sites-enabled folder
      file:
        path: /etc/nginx/sites-enabled
        state: absent
    - name: Create folder /etc/nginx/sites-enabled folder
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        
    - name: Remove /etc/nginx/sites-available folder
      file:
        path: /etc/nginx/sites-available
        state: absent
    - name: Create folder /etc/nginx/sites-available folder
      file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Upload Nginx configuration file
      copy:
        src: configs/nginxonport8000.conf
        dest: /etc/nginx/sites-available/mywebsite.conf

    - name: Creating a symlink
      ansible.builtin.file:
        src: /etc/nginx/sites-available/mywebsite.conf
        dest: /etc/nginx/sites-enabled/mywebsite.conf
        state: link
        force: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted
